name: build push docker

on:
    workflow_call:
        outputs:
            builtImgName:
                description: 'resulting image name'
                value: ${{ jobs.build_docker_image.outputs.dockerImgName }}
                
        secrets:
             hubID:
                 required: true
             hubTOKEN:
                 required: true
        
jobs:
    build_docker_image:
        name: build docker image for image repository
        runs-on: ubuntu-latest
        outputs:
            dockerImgName: ${{  steps.imagetag.outputs.builtImgName }}
        steps:    
          - name: Checkout
            uses: actions/checkout@v4.1.2
            
          - name: Setup Node.js environment
            uses: actions/setup-node@v4.0.2
            
          - name: install runtime dependencies only
            run: npm i --omit=dev
            
          - name: Docker Login
            uses: docker/login-action@v3.1.0
            with:
              username: ${{ secrets.hubID }}
              password: ${{ secrets.hubTOKEN }}
              
          - name: Docker Setup Buildx
            uses: docker/setup-buildx-action@v3.2.0
        
          - name: build the push to docker hub
            id: imagetag
            uses: docker/build-push-action@v5.3.0
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.hubID }}/external:g.${{ github.run_number }} >> $GITHUB_OUTPUT
