name: Node.js Package

on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --omit=dev
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
