name: npm install test

on:
  workflow_call:
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: install node dependencies for testing
        run: npm install

      - name: run node tests to audit codebase
        run: npm test
