name: PaaS

on:
  workflow_dispatch:
    
jobs:

  test_code_changes:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: install node dependencies for testing
        run: npm install

      - name: run node tests to audit codebase
        run: npm test

  build_docker_image:
  
    name: build docker image for image repository
    needs: [test_code_changes]
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.1.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        
      - name: install runtime dependencies only
        run: npm i --omit=dev
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: build the push to docker hub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_ID }}/external:g.${{ github.run_number }}
